environment: ccin2p3test
fqdn: kubernetes.docker.internal
vault_path_prefix: secret/k8s_operator/rsp-cc

argo:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
landing_page:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: false
ingress_nginx:
  enabled: false
nublado:
  enabled: false
obstap:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: false
squash_api:
  enabled: false
tap:
  enabled: false
vault_secrets_operator:
  enabled: true
